find_program(CORE_TESTAMENT_GXX NAMES g++ REQUIRED)

set(CMAKE_CXX_COMPILER "${CORE_TESTAMENT_GXX}" CACHE FILEPATH "C++ compiler" FORCE)
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "Disable compiler extensions" FORCE)

if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Build type" FORCE)
endif()
